// 全国机场数据
export const airports = [
    // { value: '北京 (PEK)', code: 'PEK' },
    // { value: '上海 (SHA)', code: 'SHA' },
    // { value: '广州 (CAN)', code: 'CAN' },
    // { value: '深圳 (SZX)', code: 'SZX' },
    // { value: '成都 (CTU)', code: 'CTU' },
    // { value: '杭州 (HGH)', code: 'HGH' },
    // { value: '南京 (NKG)', code: 'NKG' },
    // { value: '西安 (XIY)', code: 'XIY' },
    // { value: '武汉 (WUH)', code: 'WUH' },
    // { value: '青岛 (TAO)', code: 'TAO' },
    // { value: '昆明 (KMG)', code: 'KMG' },
    // { value: '重庆 (CKG)', code: 'CKG' },
    // { value: '天津 (TSN)', code: 'TSN' },
    // { value: '长沙 (CSX)', code: 'CSX' },
    // { value: '沈阳 (SHE)', code: 'SHE' },
    // { value: '大连 (DLC)', code: 'DLC' },
    // { value: '厦门 (XMN)', code: 'XMN' },
    // { value: '哈尔滨 (HRB)', code: 'HRB' },
    // { value: '郑州 (CGO)', code: 'CGO' },
    // { value: '福州 (FOC)', code: 'FOC' },
    // { value: '太原 (TYN)', code: 'TYN' },
    // { value: '乌鲁木齐 (URC)', code: 'URC' },
    // { value: '南宁 (NNG)', code: 'NNG' },
    // { value: '海口 (HAK)', code: 'HAK' },
    // { value: '贵阳 (KWE)', code: 'KWE' },
    // { value: '兰州 (LHW)', code: 'LHW' },
    // { value: '南昌 (KHN)', code: 'KHN' },
    // { value: '银川 (INC)', code: 'INC' },
    // { value: '呼和浩特 (HET)', code: 'HET' },
    // { value: '石家庄 (SJW)', code: 'SJW' },
    // { value: '合肥 (HFE)', code: 'HFE' },
    // { value: '宁波 (NGB)', code: 'NGB' },
    // { value: '温州 (WNZ)', code: 'WNZ' },
    // { value: '三亚 (SYX)', code: 'SYX' },
    // { value: '长春 (CGQ)', code: 'CGQ' },
    // { value: '桂林 (KWL)', code: 'KWL' },
    // { value: '珠海 (ZUH)', code: 'ZUH' },
    // { value: '西宁 (XNN)', code: 'XNN' },
    // { value: '南宁 (NNG)', code: 'NNG' },
    // { value: '西双版纳 (JHG)', code: 'JHG' },
    // { value: '丽江 (LJG)', code: 'LJG' },
    // { value: '张家界 (DYG)', code: 'DYG' },
    // { value: '烟台 (YNT)', code: 'YNT' },
    // { value: '常州 (CZX)', code: 'CZX' },
    // { value: '徐州 (XUZ)', code: 'XUZ' },
    // { value: '泉州 (JJN)', code: 'JJN' },
    // { value: '揭阳 (SWA)', code: 'SWA' },
    // { value: '连云港 (LYG)', code: 'LYG' },
    // { value: '南通 (NTG)', code: 'NTG' },
    // { value: '无锡 (WUX)', code: 'WUX' },
    // { value: '赣州 (KOW)', code: 'KOW' },
    // { value: '桂林 (KWL)', code: 'KWL' },
    // { value: '北海 (BHY)', code: 'BHY' },
    // { value: '柳州 (LZH)', code: 'LZH' },
    // { value: '桂林 (KWL)', code: 'KWL' },
{'value': '华盛顿(首都) (WAS/IAD)', 'code': 'WAS/IAD'},
{'value': '阿伦敦 (ABE)', 'code': 'ABE'},
{'value': '阿尔伯克斯 (ABQ)', 'code': 'ABQ'},
{'value': '阿特兰大 (ATL)', 'code': 'ATL'},
{'value': '奥斯汀 (AUS)', 'code': 'AUS'},
{'value': '卡拉马祖 (AZO)', 'code': 'AZO'},
{'value': '哈特福德 (BDL)', 'code': 'BDL'},
{'value': '伯明翰 (BHM)', 'code': 'BHM'},
{'value': '纳什维尔 (BNA)', 'code': 'BNA'},
{'value': '博伊西 (BOI)', 'code': 'BOI'},
{'value': '波士顿 (BOS)', 'code': 'BOS'},
{'value': '布朗斯韦尔 (BRO)', 'code': 'BRO'},
{'value': '巴吞鲁日 (BTR)', 'code': 'BTR'},
{'value': '巴特尔克里克 (BTL)', 'code': 'BTL'},
{'value': '布法罗 (BUF)', 'code': 'BUF'},
{'value': '巴尔的摩 (BWI)', 'code': 'BWI'},
{'value': '哥伦比亚 (CAE)', 'code': 'CAE'},
{'value': '阿克伦肯顿 (CAK)', 'code': 'CAK'},
{'value': '查塔诺加 (CHA)', 'code': 'CHA'},
{'value': '芝加哥 (CHI/ORD)', 'code': 'CHI/ORD'},
{'value': '查尔斯顿 (CHS)', 'code': 'CHS'},
{'value': '锡达拉皮兹 (CID)', 'code': 'CID'},
{'value': '克利夫兰 (CLE)', 'code': 'CLE'},
{'value': '夏洛特 (CLT)', 'code': 'CLT'},
{'value': '哥伦布 (CMH)', 'code': 'CMH'},
{'value': '科珀斯克里斯蒂 (CRP)', 'code': 'CRP'},
{'value': '辛辛那提 (CVG)', 'code': 'CVG'},
{'value': '代顿 (DAY)', 'code': 'DAY'},
{'value': '丹佛 (DEN)', 'code': 'DEN'},
{'value': '达拉斯 (DFW)', 'code': 'DFW'},
{'value': '得梅因 (DSM)', 'code': 'DSM'},
{'value': '底特律 (DTW/DTT)', 'code': 'DTW/DTT'},
{'value': '埃尔帕索 (ELP)', 'code': 'ELP'},
{'value': '伊利/伊利湖 (ERI)', 'code': 'ERI'},
{'value': '纽瓦克 (EWR)', 'code': 'EWR'},
{'value': '埃文斯韦尔 (EVV)', 'code': 'EVV'},
{'value': '劳德代尔堡 (FLL)', 'code': 'FLL'},
{'value': '弗林特 (FNT)', 'code': 'FNT'},
{'value': '育空堡 (FWA)', 'code': 'FWA'},
{'value': '北卡罗来纳州 (FWA)', 'code': 'FWA'},
{'value': '大急流域 (GRR)', 'code': 'GRR'},
{'value': '斯波坎 (GEG)', 'code': 'GEG'},
{'value': '格林斯伯勒 (GSO)', 'code': 'GSO'},
{'value': '格林维尔 (GSP)', 'code': 'GSP'},
{'value': '格林贝 (GRB)', 'code': 'GRB'},
{'value': '哈特福德 (HFD)', 'code': 'HFD'},
{'value': '休斯敦 (HOU/IAH)', 'code': 'HOU/IAH'},
{'value': '亨茨维尔 (HSV)', 'code': 'HSV'},
{'value': '火奴鲁鲁（夏威夷州的首府) (HNL)', 'code': 'HNL'},
{'value': '威奇托 (ICT)', 'code': 'ICT'},
{'value': '威尔明顿 (ILM)', 'code': 'ILM'},
{'value': '印第安纳波利斯 (IND)', 'code': 'IND'},
{'value': '杰克逊 (JAN)', 'code': 'JAN'},
{'value': '杰克逊威尔 (JAX)', 'code': 'JAX'},
{'value': '拉斯维加斯 (LAS)', 'code': 'LAS'},
{'value': '洛杉机 (LAX)', 'code': 'LAX'},
{'value': '列克星敦 (LEX)', 'code': 'LEX'},
{'value': '小石城 (LIT)', 'code': 'LIT'},
{'value': '林肯 (LNK)', 'code': 'LNK'},
{'value': '拉雷多 (LRD)', 'code': 'LRD'},
{'value': '堪萨斯城 (MCI)', 'code': 'MCI'},
{'value': '奥兰多 (MCO)', 'code': 'MCO'},
{'value': '孟菲斯 (MEM)', 'code': 'MEM'},
{'value': '麦卡伦 (MFE)', 'code': 'MFE'},
{'value': '迈阿密 (MIA)', 'code': 'MIA'},
{'value': '堪萨斯 (MKC)', 'code': 'MKC'},
{'value': '密尔沃基 (MKE)', 'code': 'MKE'},
{'value': '麦迪逊 (MSN)', 'code': 'MSN'},
{'value': '明利阿波利斯 (MSP)', 'code': 'MSP'},
{'value': '新奥尔良 (MSY)', 'code': 'MSY'},
{'value': '莫比尔 (MOB)', 'code': 'MOB'},
{'value': '纽约 (NYC/JFK)', 'code': 'NYC/JFK'},
{'value': '长滩 (LGB)', 'code': 'LGB'},
{'value': '俄克拉荷马城 (OKC)', 'code': 'OKC'},
{'value': '奥马哈 (OMA)', 'code': 'OMA'},
{'value': '诺福克 (ORF)', 'code': 'ORF'},
{'value': '奥兰多 (ORL)', 'code': 'ORL'},
{'value': '西棕榈滩 (PBI)', 'code': 'PBI'},
{'value': '波特兰 (PDX/PWM)', 'code': 'PDX/PWM'},
{'value': '费城 (PHL/PHA)', 'code': 'PHL/PHA'},
{'value': '费尼克斯 (PHX)', 'code': 'PHX'},
{'value': '皮奥里亚 (PIA)', 'code': 'PIA'},
{'value': '匹兹堡 (PIT)', 'code': 'PIT'},
{'value': '彭萨科拉 (PNS)', 'code': 'PNS'},
{'value': '普罗维登斯 (PVD)', 'code': 'PVD'},
{'value': '达拉谟 (RDU)', 'code': 'RDU'},
{'value': '里士满 (RIC)', 'code': 'RIC'},
{'value': '里诺 (RNO)', 'code': 'RNO'},
{'value': '罗彻斯特 (ROC)', 'code': 'ROC'},
{'value': '圣迭戈 (SAN)', 'code': 'SAN'},
{'value': '圣安东尼奥 (SAT)', 'code': 'SAT'},
{'value': '萨凡纳 (SAV)', 'code': 'SAV'},
{'value': '南本德 (SBN)', 'code': 'SBN'},
{'value': '路易斯维尔 (SDF)', 'code': 'SDF'},
{'value': '西雅图 (SEA)', 'code': 'SEA'},
{'value': '西雅图 (BFI)', 'code': 'BFI'},
{'value': '旧金山 (SFO)', 'code': 'SFO'},
{'value': '斯普林菲尔德 (SGF)', 'code': 'SGF'},
{'value': '什里夫波特 (SHV)', 'code': 'SHV'},
{'value': '盐湖城 (SLC)', 'code': 'SLC'},
{'value': '萨克拉门托 (SMF)', 'code': 'SMF'},
{'value': '圣路易斯 (STL)', 'code': 'STL'},
{'value': '塔尔萨 (TUL)', 'code': 'TUL'},
{'value': '锡拉丘兹 (SYR)', 'code': 'SYR'},
{'value': '托莱多 (TOL)', 'code': 'TOL'},
{'value': '坦帕 (TPA)', 'code': 'TPA'},
{'value': '塔尔萨 (TUL)', 'code': 'TUL'},
{'value': '图森 (TUS)', 'code': 'TUS'},
{'value': '诺科斯韦尔 (TYS)', 'code': 'TYS'}
];